-- GENERATED by gen-ahvalue-addon.sh -- do not hand-edit, rerun the script.
-- Buyer multipliers, mirrored from acore_world.mod_auctionhousebot (house 7).
NorgAHValue_Mult = {
  [0] = 1,   -- poor
  [1] = 3,   -- common
  [2] = 5,  -- uncommon
  [3] = 12,   -- rare
  [4] = 20,   -- epic
  [5] = 40,   -- legendary
  [6] = 60,   -- artifact
  [7] = 60,   -- heirloom (shares the artifact multiplier upstream)
}
